name: DrQA 
channels:
 - conda-forge
 - soumith
dependencies:
  - python=3.6
  - numpy=1.11.*
  - spacy=1.8.*
  - scipy=0.19.*
  - scikit-learn=0.18.*
  - cython=0.25.* 
  - pytest=3.1.*
  - coverage
  - pytorch 
  - torchvision
  - pip:
    - tqdm  
    - mypy
    - regex
    - termcolor
    - prettytable
    - pexpect  

